version: '3.8'

services:
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'parts_db'
            MYSQL_ROOT_PASSWORD: 'password'
        expose:
            - '3306'
        volumes:
            - mysqldata:/data/mysql

    redis:
        image: redis
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redisdata:/data

    mongodb:
        image: mongo:6
        container_name: mongo-local
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: logs_db
        volumes:
            - mongo_data:/data/db

    app:
        build: .
        container_name: api-auto-parts
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        depends_on:
            - mysql-db
            - redis
        command:
            /usr/app/wait-for-it.sh mysql-db:3306 -- /usr/app/wait-for-it.sh redis:6379 -- npm start

volumes:
    mysqldata:
    redisdata:
    mongo_data:
